server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      httpclient:
        # 设置超时时间
#        connect-timeout: 2
#        response-timeout: 1s
      discovery:
        locator:
          #是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能
          enabled: true
          #开启小写，#路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          lower-case-service-id: true
      routes:
        - id: Pay-Route
          # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是需要转发到的服务名称
          uri: lb://pay
          predicates:
            # 定义匹配规则，满足/pay/**的路径都会被转发到uri的配置服务去
            - Path=/pay/**
          # 去掉uri路径中的服务名
          filters:
            - StripPrefix=1
          # 第二个服务的路由规则
        - id: Order-Route
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1

logging:
  level:
    com: debug
    org: debug
